{
  parserClass="guru.qas.martini.gherkin.GherkinParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Gherkin"
  psiImplClassSuffix="Impl"
  psiPackage="guru.qas.martini.gherkin.psi"
  psiImplPackage="guru.qas.martini.gherkin.psi.impl"

  elementTypeHolderClass="guru.qas.martini.gherkin.psi.GherkinTypes"
  elementTypeClass="guru.qas.martini.gherkin.psi.GherkinElementType"
  tokenTypeClass="guru.qas.martini.gherkin.psi.GherkinTokenType"

  tokens = [
      KEYWORD_FEATURE='Feature'
      KEYWORD_SEPARATOR=':'
      space='regexp:\s+'
      word='regexp:\w+'
  ]
}


gherkinFile ::= space? feature
feature ::= tags? KEYWORD_FEATURE separator title

tags ::= {space|tag}*
tag ::= '@' word modifier?
modifier ::= "('" word "')"

separator ::= space? ":" space?
title ::= {space|word}*


//gherkinFile ::= item_*

//private item_ ::= (property|COMMENT|CRLF)

//property ::= (KEY? SEPARATOR VALUE?) | KEY